version: '3'
services:
  front:
    build: "./front"
    ports:
      - "80:80"
  
  back:
    build: './backend'
    ports:
      - 8197:8197
    depends_on: 
      - db

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'root'
      MYSQL_ROOT_PASSWORD: 'ssafy'
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306